### ISSUE TITLE
希望增加文字长度上限

### ISSUE THREAD

**Issue by uniqueww** [bestZwei/ciallo-tts#1]
目前有字符限制，大概看了一下您的代码
发现请求api使用的是get方法，长度过长会报error
期待您的优化

**Comment by bestZwei** [comment]
问题是，api 返回的音频最长10分钟

**Comment by bestZwei** [comment]
你试试，做了个智能分段，2500中文字符，或者5000其他字符，分成一段。长文本将自动切分，优先根据分段-句号-逗号切分

**Comment by uniqueww** [comment]
> 你试试，做了个智能分段，2500中文字符，或者5000其他字符，分成一段。长文本将自动切分，优先根据分段-句号-逗号切分

好的，原来是api的返回限制了字符，我尝试优化一下，感谢你的回复
