### ISSUE TITLE
cf部署，Workers API无法使用，提示401。但是Deno API正常。

### ISSUE THREAD

**Issue by Yortl** [bestZwei/ciallo-tts#3]
使用你的网站（https://tts.ciallo.de/）Workers API请求是正常的，是api做了什么限制吗？

**Comment by bestZwei** [comment]
对，有人使劲刷我的 workers，故增加了认证token。
https://github.com/bestZwei/ciallo-tts/commit/530a59e4e42b3ff06fb1f90aef2fffa72da9e498
